info:
  app.name: Starter
  app.description: Ext JS 6 classic starter application
  app.version: 1.0.0

app:
  url: http://localhost:8080
  rememberme-cookie-key: starter
  rememberme-cookie-valid-in-days: 31
  default-email-sender: no-reply@starter.com
  login-lock-attempts: 10
  login-lock-minutes: 30

security:
  ignored:
    - /resources/**
    - /app.js
    - /app.json
    - /locale-de.js
    - /i18n-de.js
    - /i18n-en.js

spring:
  jackson:
    serialization:
      write-date-timestamps-as-nanoseconds: false
  
  resources:
    cache-period: 31556926
  
  mvc:
    favicon:
      enabled: false

  mail:
    host: localhost    

  data:
    mongodb:
      uri: mongodb://localhost/starter6?w=1&wtimeoutMS=0&journal=true

  async:
    core-pool-size: 2
    max-pool-size: 20
    queue-capacity: 200
    thread-name-prefix: starter-async-executor

  main:
    banner-mode: log 


server:
  port: 80
  session-timeout: 480
  compression:
     enabled: true
     mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript
  use-forward-headers: true

    
logging:
  level:
    org.springframework: WARN
    org.mongodb: WARN
    org.apache: WARN
    ch: WARN
  file: ./app.log
