spring:
  resources:
    cache-period:

security:
  ignored:
    - /resources/**
    - /build/**
    - /ext/**
    - /**/*.js
    - /bootstrap.json

server:
  port: 8080
  compression:
    enabled: false

logging:
  level:
    org.mongodb.driver.protocol: DEBUG
    org.springframework: INFO
    org.apache: INFO
    ch: INFO
