spring:
  resources:
    cache-period: 0
    static-locations: file:./client/
  jpa:
    show-sql: true

server:
  port: 8080
  compression:
    enabled: false

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework: INFO
    org.apache: INFO
    ch: INFO
